<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                      http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.emergent.its.gittle</groupId>
  <artifactId>project-with-hash</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <properties>
    <revision>0.0.0-SNAPSHOT</revision>
    <maven.compiler.release>17</maven.compiler.release>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>@project.groupId@</groupId>
        <artifactId>gittle-maven-plugin</artifactId>
        <version>@project.version@</version>
        <extensions>true</extensions>
        <configuration>
          <strategy hint="git">
            <nonQualifierBranches>main,master</nonQualifierBranches>
            <snapshot>true</snapshot>
          </strategy>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
